import = [
  "~/.config/alacritty/colors/color.toml"
]

live_config_reload = true

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[shell]
program = "/usr/bin/fish"
args = ["--login", "--interactive"]

[window]
decorations = "none"

[window.padding]
x = 5
y = 5

[mouse]
hide_when_typing = true

[font]
size = 12

[font.offset]
x = 0
y = 0

[font.normal]
family = "Iosevka Term"
style = "Regular"

# [font.bold]
# family = "Iosevka Term"
# style = "Bold"
#
# [font.italic]
# family = "Iosevka Term"
# style = "Italic"
#
# [font.bold_italic]
# family = "Iosevka Term"
# style = "BoldItalic"

[[keyboard.bindings]]
key = "Key0"
mods = "Control|Alt"
command = { program = "alacritty", args = ["msg", "config", "-r"] }

[[keyboard.bindings]]
key = "Key1"
mods = "Control"
command = { program = "alacritty", args = ["msg", "config", "font.size=16"] }

[[keyboard.bindings]]
key = "Key2"
mods = "Control"
command = { program = "alacritty", args = ["msg", "config", "font.size=20"] }

[[keyboard.bindings]]
key = "Key3"
mods = "Control"
command = { program = "alacritty", args = ["msg", "config", "font.size=24"] }
